name: alexraylib # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  alexraylib:
    command: usr/local/bin/alexRaylibTest
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - home
    environment:
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
      MESA_LOADER_DRIVER_OVERRIDE: iris
      LIBGL_DEBUG: verbose

parts:
  alexraylib:
    plugin: cmake
    source: .  # Cambia esta ruta según la ubicación de tu proyecto
    build-packages:
      - cmake
      - make
      - gcc
      - ninja-build
      - python3
      - python3-venv
      - pkg-config
      - libx11-dev   # Paquete necesario para compilar con X11
      - libgl-dev
      - libgl1-mesa-dev
      - libx11-xcb-dev
      - libfontenc-dev
      - libice-dev
      - libsm-dev
      - libxaw7-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbfile-dev
      - libxmu-dev
      - libxmuu-dev
      - libxpm-dev
      - libxrandr-dev
      - libxrender-dev
      - libxres-dev
      - libxss-dev
      - libxt-dev
      - libxtst-dev
      - libxv-dev
      - libxxf86vm-dev
      - libxcb-glx0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-xkb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shape0-dev
      - libxcb-sync-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-dri3-dev
      - uuid-dev
      - libxcb-cursor-dev
      - libxcb-dri2-0-dev
      - libxcb-dri3-dev
      - libxcb-present-dev
      - libxcb-composite0-dev
      - libxcb-ewmh-dev
      - libxcb-res0-dev
      - libxcb-util-dev
      - libxcb-util-dev
    stage-packages:
      - libx11-6
      - libc6
      - libgl1-mesa-dri
      - libglu1-mesa
      - libglfw3
      - libxcb1
      - libxrandr2
      - libxinerama1
      - libxcursor1
      - libglu1-mesa
      - libgl1
      - libglx-mesa0
      - libgl1-mesa-dri
      - libxxf86vm1
      - libxrender1
      - libxdamage1
      - libdrm2
      - libxcb-dri3-0
      - libxcb-dri2-0
      - libxcb-present0

    override-build: |
      # Crear un entorno virtual para Conan
      python3 -m venv venv
      source venv/bin/activate

      # Instalar Conan en el entorno virtual
      pip install conan

      # Configurar CMake con las dependencias de Conan
      cmake -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake \
            -S /root/parts/alexraylib/src/ \
            -G "Unix Makefiles"
      snapcraftctl build
    organize:
      snap/gui/alexraylib.desktop: meta/gui/alexraylib.desktop
      snap/gui/alexraylib.png: meta/gui/alexraylib.png


